apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-nov6-3-l 
  janus-idp.io/tekton: rag-nov6-3-l
  backstage.io/kubernetes-id: rag-nov6-3-l
  backstage.io/kubernetes-namespace: rag-nov6-3-l 
  app.kubernetes.io/part-of: rag-nov6-3-l
resources: 
- application-dev.yaml