kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rag-nov6-3-l-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: rag-nov6-3-l-dsp-job
    namespace: rag-nov6-3-l
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rag-nov6-3-l-dsp-job-role